# Generated by Django 5.2.6 on 2025-09-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('cached_requests', models.IntegerField(default=0)),
                ('api_requests', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('total_products_returned', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('timeout_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_usage_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('product_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_price', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source', models.CharField(max_length=200)),
                ('source_icon', models.URLField(blank=True, null=True)),
                ('multiple_sources', models.BooleanField(default=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('product_link', models.URLField()),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='products_title_6a4e5e_idx'), models.Index(fields=['source'], name='products_source_6b8d10_idx'), models.Index(fields=['rating'], name='products_rating_53cb37_idx'), models.Index(fields=['extracted_price'], name='products_extract_fc5502_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('query', models.CharField(max_length=500)),
                ('results', models.JSONField()),
                ('results_count', models.IntegerField()),
                ('response_time_ms', models.IntegerField()),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('hit_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'product_cache',
                'ordering': ['-cached_at'],
                'indexes': [models.Index(fields=['query_hash'], name='product_cac_query_h_576142_idx'), models.Index(fields=['expires_at'], name='product_cac_expires_0af13f_idx'), models.Index(fields=['hit_count'], name='product_cac_hit_cou_5720da_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=500)),
                ('query_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('search_count', models.IntegerField(default=1)),
                ('last_searched', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('results_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'search_queries',
                'ordering': ['-last_searched'],
                'indexes': [models.Index(fields=['query_hash'], name='search_quer_query_h_45d1f4_idx'), models.Index(fields=['search_count'], name='search_quer_search__9e0605_idx'), models.Index(fields=['last_searched'], name='search_quer_last_se_645bbf_idx')],
            },
        ),
    ]
